### ISSUE TITLE
Crypto Package - Historical Data - Error: HTTP status was '403 Forbidden'

### ISSUE THREAD

**Issue by PatRick2409** [JesseVent/crypto#13]
Dear Users, 

Since 1 day I get the following error when I try to download historical data via the 'crypto' Package:

Error in open.connection(con, "rb") : cannot open the connection
In addition: Warning message:
In open.connection(con, "rb") :
  cannot open URL 'https://files.coinmarketcap.com/generated/search/quick_search.json': HTTP status was '403 Forbidden'

I also tried this via a different IP address, but it is unfortunately also not working. Is there anything we could do?

Best regards, 
Patrick

**Comment by JesseVent** [comment]
Yeah CoinMarketCap changed one of their services, I’ve already uploaded fix for it to GitHub and submitted for CRAN approval.

For now install dev version from github

Thanks

**Comment by PatRick2409** [comment]
Alright, thank you very much!

**Comment by JesseVent** [comment]
Hi @PatRick2409, update deployed to CRAN, did the latest patch resolve your issue? Thanks

**Comment by scott-linford** [comment]
Hi all,

I'm still getting this error despite pulling the most recent version from Github, could CMC have changed something on their end again?

Cheers,
Scott

**Comment by JesseVent** [comment]
In the packages window what version of crypto does it say you’re running? Maybe delete package and reinstall because that URL definitely isn’t used anymore. 

I ran it about 5 minutes ago so definitely no issues with api.

After trying that, if it still doesn’t work please run traceback() afterwards and post results.
