### ISSUE TITLE
contact with JesseVent

### ISSUE THREAD

**Issue by mprekr** [JesseVent/crypto#15]
Dear Jesse,

I am writting because I am a student that is currently involved in R studio for an empirical papper at my University. The papper name is "Portfolio Management and Investment Strategies for Crypto-Assets". We are also using your tools from: https://github.com/JesseVent/crypto/.

Will you be so kind and would you like to have a small conversation with me because I have some questions to the code regarding my papper and I am stuck in the coding process.

kind regards
mprekr

**Comment by JesseVent** [comment]
Sure, how can I help?

**Comment by JesseVent** [comment]
Hi,

I added a new function tonight to the package that should do what you're after

Try give the following code a try. 

```R
devtools::install_github("jessevent/crypto")
library(crypto)
df        <- getCoins()
day_xts   <- crypto2xts(df, "day")
week_xts  <- crypto2xts(df, "week")
month_xts <- crypto2xts(df, "month")
```

Out of curiosity has your university directed you to this package or did you choose it yourself?

**Comment by mprekr** [comment]
Hey Jesse,

The University directed us to your page becasue as Finance students we need
also to code. By the way, are you searching for someone to your company
currently that is mixing finance and data science? I would be more than
happy to apply if its possible.


kind regards
mprekr

2018-04-15 18:01 GMT+02:00 Jesse <notifications@github.com>:

**Comment by mprekr** [comment]
Dear Jesse,

I have some errors after applying the new code. In attachment the code and
a print screen from errors. I am currently working on it but for now I do
not have a solution to it. Do you have maybe any suggestions?


kind regards
mprekr

2018-04-15 18:50 GMT+02:00 MP PM <mprekr@gmail.com>:

**Comment by JesseVent** [comment]
Can you please paste the errors as I cant view attachments

**Comment by mprekr** [comment]
> day_xts   <- crypto2xts(df, "day")Error in crypto2xts(df, "day") : could not find function "crypto2xts"> week_xts  <- crypto2xts(df, "week")Error in crypto2xts(df, "week") : could not find function "crypto2xts"> month_xts <- crypto2xts(df, "month")Error in crypto2xts(df, "month") : could not find function "crypto2xts"



2018-04-16 0:28 GMT+02:00 Jesse <notifications@github.com>:

**Comment by JesseVent** [comment]
Have you installed version 1.6 from github repo? `devtools::install_github("jessevent/crypto")`

**Comment by mprekr** [comment]
another error

devtools::install_github("jessevent/crypto")Error in
loadNamespace(name) : there is no package called ‘devtools’



2018-04-16 0:39 GMT+02:00 Jesse <notifications@github.com>:

**Comment by JesseVent** [comment]
`install.packages("devtools")`
`devtools::install_github("jessevent/crypto")`

**Comment by mprekr** [comment]
Downloading GitHub repo jessevent/crypto@master
from URL https://api.github.com/repos/jessevent/crypto/zipball/masterInstalling
crypto"E:/Program Files/R/R-3.4.1/bin/x64/R" --no-site-file
--no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/Cesar/AppData/Local/Temp/Rtmp8UQTZ4/devtools125075b66459/JesseVent-crypto-8046b42"
 \
  --library="E:/Program Files/R/R-3.4.1/library" --install-tests
'E:\Program' is not recognized as an internal or external command,
operable program or batch file.Installation failed: Command failed (1)



2018-04-16 0:42 GMT+02:00 Jesse <notifications@github.com>:

**Comment by JesseVent** [comment]
ahh your using windows, I think it could be an issue with the devtools library

https://github.com/r-lib/devtools/issues/426

View last comment and try that

**Comment by mprekr** [comment]
Dear Jesse,

I am an IT noob (sadly) therefore the majority of this last comment is
unclear to me what should I do. I am currently installing the java package
but from point 2 "Install "Rtools34" its getting unclear what should I do.

Therefore, could you please kindly help me how should I proceed with this?


kind regards
mprekr



2018-04-16 0:51 GMT+02:00 Jesse <notifications@github.com>:

**Comment by JesseVent** [comment]
https://cran.r-project.org/bin/windows/Rtools/

**Comment by mprekr** [comment]
ok Im installing Rtools34.exe
<https://cran.r-project.org/bin/windows/Rtools/Rtools34.exe>

2018-04-16 1:13 GMT+02:00 Jesse <notifications@github.com>:

**Comment by mprekr** [comment]
Dear Jesse,

I can't find:
basic-miktex-2.9.6236-x64

do you know where I can find it? The comand from this webpage does not work
(https://chocolatey.org/packages/miktex.install/2.9.6236)

kr
mprekr

2018-04-16 1:16 GMT+02:00 MP PM <mprekr@gmail.com>:

**Comment by JesseVent** [comment]
This is the raw function, try this
```
crypto2xts <- function(df, frequency = NULL) {
  slug        <- ""
  symbol      <- ""
  name        <- ""
  ranknow     <- ""
  high        <- ""
  low         <- ""
  market      <- ""
  volume      <- ""
  freq        <- frequency
  df$date     <- lubridate::round_date(df$date, freq)
  data        <-
    df %>% dplyr::group_by(date, slug, symbol, name, ranknow) %>% dplyr::summarise(
      open   = dplyr::first(open),
      high   = max(high),
      low    = min(low),
      close  = dplyr::last(close),
      volume = sum(volume),
      market = dplyr::last(market))
  data$volume <- round(data$volume, digits = 0)
  data$market <- round(data$market, digits = 0)
  data        <- as.data.frame(data)
  results <- xts::xts(data[, 2:ncol(data)], as.POSIXct(data[, 1], format = "%d.%m.%Y %H:%M:%S"))
  return(results)
}
```

**Comment by mprekr** [comment]
> install.packages("Rtools34")Warning in install.packages :
  package ‘Rtools34’ is not available (for R version 3.4.1)



2018-04-16 1:54 GMT+02:00 Jesse <notifications@github.com>:

**Comment by mprekr** [comment]
I used the code that you provided  from the email " This is the raw
function, try this" its creating a function. How should I proceed further?


kr
mprekr

2018-04-16 2:01 GMT+02:00 MP PM <mprekr@gmail.com>:

**Comment by mprekr** [comment]
The whole code looks like this currently:

install.packages("crypto")
install.packages("xts")
install.packages("tidyr")

require(crypto)
require(xts)
require(tidyr)

crypto2xts <- function(df, frequency = NULL) {
  slug        <- ""
  symbol      <- ""
  name        <- ""
  ranknow     <- ""
  high        <- ""
  low         <- ""
  market      <- ""
  volume      <- ""
  freq        <- frequency
  df$date     <- lubridate::round_date(df$date, freq)
  data        <-
    df %>% dplyr::group_by(date, slug, symbol, name, ranknow) %>%
dplyr::summarise(
      open   = dplyr::first(open),
      high   = max(high),
      low    = min(low),
      close  = dplyr::last(close),
      volume = sum(volume),
      market = dplyr::last(market))
  data$volume <- round(data$volume, digits = 0)
  data$market <- round(data$market, digits = 0)
  data        <- as.data.frame(data)
  results <- xts::xts(data[, 2:ncol(data)], as.POSIXct(data[, 1], format =
"%d.%m.%Y %H:%M:%S"))
  return(results)
}

install.packages("devtools")
devtools::install_github("jessevent/crypto")
df        <- getCoins()
day_xts   <- crypto2xts(df, "day")
week_xts  <- crypto2xts(df, "week")
month_xts <- crypto2xts(df, "month")



but it still gives me an error at line:

> devtools::install_github("jessevent/crypto")Downloading GitHub repo jessevent/crypto@master
from URL https://api.github.com/repos/jessevent/crypto/zipball/masterInstalling
crypto"E:/Program Files/R/R-3.4.1/bin/x64/R" --no-site-file
--no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/Cesar/AppData/Local/Temp/Rtmp2XMb68/devtoolsac45b3744cf/JesseVent-crypto-8046b42"
 \
  --library="E:/Program Files/R/R-3.4.1/library" --install-tests
'E:\Program' is not recognized as an internal or external command,
operable program or batch file.Installation failed: Command failed (1)



2018-04-16 2:04 GMT+02:00 MP PM <mprekr@gmail.com>:

**Comment by mprekr** [comment]
Dear Jesse,

I runed the code once more. It trigers an error at line
devtools::install_github("hadley/devtools"):

Installation failed: Command failed (1)Downloading GitHub repo
r-lib/pkgload@master
from URL https://api.github.com/repos/r-lib/pkgload/zipball/mastertrying
URL 'https://cran.rstudio.com/bin/windows/Rtools/Rtools34.exe'Content
type 'application/x-msdos-program' length 108085090 bytes (103.1
MB)downloaded 103.1 MB



also the line: devtools::install_github("jessevent/crypto") trigers an
error:

> devtools::install_github("jessevent/crypto")Downloading GitHub repo jessevent/crypto@master
from URL https://api.github.com/repos/jessevent/crypto/zipball/masterInstalling
crypto"E:/Program Files/R/R-3.4.1/bin/x64/R" --no-site-file
--no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/Cesar/AppData/Local/Temp/RtmpILvzyh/devtools2c42df7f8c/JesseVent-crypto-8046b42"
 \
  --library="E:/Program Files/R/R-3.4.1/library" --install-tests
'E:\Program' is not recognized as an internal or external command,
operable program or batch file.Installation failed: Command failed (1)



The whole code is below. Currently I have no idea what is wrong (I updated
the system as it was posted on the webpage provided by you). I am also very
thankfull for your help with providing me the links. I am workind on
Windows 10.


install.packages("crypto")
install.packages("xts")
install.packages("tidyr")

require(crypto)
require(xts)
require(tidyr)

crypto2xts <- function(df, frequency = NULL) {
  slug        <- ""
  symbol      <- ""
  name        <- ""
  ranknow     <- ""
  high        <- ""
  low         <- ""
  market      <- ""
  volume      <- ""
  freq        <- frequency
  df$date     <- lubridate::round_date(df$date, freq)
  data        <-
    df %>% dplyr::group_by(date, slug, symbol, name, ranknow) %>%
dplyr::summarise(
      open   = dplyr::first(open),
      high   = max(high),
      low    = min(low),
      close  = dplyr::last(close),
      volume = sum(volume),
      market = dplyr::last(market))
  data$volume <- round(data$volume, digits = 0)
  data$market <- round(data$market, digits = 0)
  data        <- as.data.frame(data)
  results <- xts::xts(data[, 2:ncol(data)], as.POSIXct(data[, 1], format =
"%d.%m.%Y %H:%M:%S"))
  return(results)
}


normalizePath("C:/Rtools/bin")
devtools::install_github("hadley/devtools")


install.packages("devtools")
devtools::install_github("jessevent/crypto")
df        <- getCoins()
day_xts   <- crypto2xts(df, "day")
week_xts  <- crypto2xts(df, "week")
month_xts <- crypto2xts(df, "month")

2018-04-16 2:13 GMT+02:00 MP PM <mprekr@gmail.com>:

**Comment by mprekr** [comment]
I still can't find a working  "basic-miktex-2.9.6236-x64" package and I
think that can be the issue. What is your opinion?


kind regards
mprekr

2018-04-16 13:45 GMT+02:00 MP PM <mprekr@gmail.com>:

**Comment by JesseVent** [comment]
Try running the first part of this statement. If there are no errors, then run the last two one at a time (select the statement and click run on just that line of code.

My opinion is that its probably to do with where R is trying to install the packages (On your C:// drive) compared to where R appears to be installed (E://) drive.. but try the below. I don't have any experience using R with windows so can't be much help in that department.

```R

### RUN FROM HERE -----------------------------------------------------
install.packages("dplyr", dependencies = TRUE)
install.packages("tidyverse", dependencies = TRUE)
install.packages("magrittr") 
library(magrittr)
library(dplyr)
library(tidyverse)
library(crypto)
library(lubridate)
library(xts)

df <- getCoins(limit = 50)

yourfunction <- function(df, frequency = NULL) {
  freq        <- frequency
  df$date     <- lubridate::round_date(df$date, freq)
  data        <-
    df %>% dplyr::group_by(date, slug, symbol, name, ranknow) %>%
    dplyr::summarise(
      open   = dplyr::first(open),
      high   = max(high),
      low    = min(low),
      close  = dplyr::last(close),
      volume = sum(volume),
      market = dplyr::last(market))
  data$volume <- round(data$volume, digits = 0)
  data$market <- round(data$market, digits = 0)
  data        <- as.data.frame(data)
  results <- xts::xts(data[, 2:ncol(data)], as.POSIXct(data[, 1], format =
                                                         "%d.%m.%Y %H:%M:%S"))
  return(results)
}

### TO HERE ---------------------------------------------------------------

#### IF NO ERRORS IN ABOVE RUN THESE INDIVIDUALLY------
week_xts  <- yourfunction(df, frequency = "week")

#### IF NO ERRORS IN ABOVE RUN THESE INDIVIDUALLY------
month_xts <- yourfunction(df, frequency = "month")
```

**Comment by mprekr** [comment]
Dear Jesse,

For windows it does not metter where tou dawnload the packages because you
can set a destination place for the code e.g:

setwd("E:/User/Desktop/studies/year I/semester II/seminar finance")
getwd()


I am currently running the code and I will come to you latter back with my
findings.


kind regards
mprekr

2018-04-16 18:41 GMT+02:00 Jesse <notifications@github.com>:

**Comment by mprekr** [comment]
Dear Jesse,

I se that this part: " "Best way is for all return calculation (weekly and
monthly) to refer back to the original Index and calculate the returns
based on the date series (last trading day of the week/month). As coins are
traded 24/7 this makes things easier."

Has been already done by you. Thank you once more for your help. Can I come
to you back if I will have more questions? I would also like to make a
donation for you.


kind regards
mprekr

2018-04-16 21:22 GMT+02:00 MP PM <mprekr@gmail.com>:

**Comment by mprekr** [comment]
Dear Jesse,

I would like to make a data frame for each data type (open, high, close,
volume, market, close_ratio and spread) for daily, monthly and weekly
frequencies. These data frames should be constructed in a way that each
column represents one currency and the rows would represent observations.

However, when I try to  use spread function for weekly and  monthly
frequencies in order to do this,it gives an error. How should I proceed?
Thank you in advance and have a pleasant day.


Error:

> weekly_open <- spread(week_xts[,c(1,5)],slug,open)Error in UseMethod("spread_") :
  no applicable method for 'spread_' applied to an object of class
"c('matrix', 'character')"> monthly_open <-
spread(month_xts[,c(1,5)],slug,open)Error in UseMethod("spread_") :
  no applicable method for 'spread_' applied to an object of class
"c('matrix', 'character')"




kind regards
mprekr

2018-04-17 12:20 GMT+02:00 Jesse <notifications@github.com>:

**Comment by mprekr** [comment]
Bellow the code:

setwd("E:/User/Desktop/studies/year I/semester II/seminar finance")
getwd()


install.packages("dplyr", dependencies = TRUE)
install.packages("tidyverse", dependencies = TRUE)
install.packages("magrittr")
install.packages("xts")
install.packages("PerformanceAnalytics")
install.packages("quantmod")
install.packages("tidyr")

library(magrittr)
library(dplyr)
library(tidyverse)
library(crypto)
library(lubridate)
library(xts)
library(PerformanceAnalytics)
library(quantmod)
library(tidyr)

require(magrittr)
require(dplyr)
require(tidyverse)
require(crypto)
require(lubridate)
require(xts)
require(PerformanceAnalytics)
require(quantmod)
require(tidyr)

df <- getCoins(limit = 50)


yourfunction <- function(df, frequency = NULL) {
  freq        <- frequency
  df$date     <- lubridate::round_date(df$date, freq)
  data        <-
    df %>% dplyr::group_by(date, slug, symbol, name, ranknow) %>%
    dplyr::summarise(
      open   = dplyr::first(open),
      high   = max(high),
      low    = min(low),
      close  = dplyr::last(close),
      volume = sum(volume),
      market = dplyr::last(market))
  data$volume <- round(data$volume, digits = 0)
  data$market <- round(data$market, digits = 0)
  data        <- as.data.frame(data)
  results <- xts::xts(data[, 2:ncol(data)], as.POSIXct(data[, 1], format =
                                                         "%d.%m.%Y
%H:%M:%S"))
  return(results)
}

#### IF NO ERRORS IN ABOVE RUN THESE INDIVIDUALLY------
week_xts  <- yourfunction(df, frequency = "week")


#### IF NO ERRORS IN ABOVE RUN THESE INDIVIDUALLY------
month_xts <- yourfunction(df, frequency = "month")


daily_open <- spread(df[,c(1,4,6)],slug,open)
weekly_open <- spread(week_xts[,c(1,5)],slug,open)
monthly_open <- spread(month_xts[,c(1,5)],slug,open)

2018-04-29 22:50 GMT+02:00 MP PM <mprekr@gmail.com>:

**Comment by JesseVent** [comment]
Sorry not a use case I've come across before, look up transposing xts or matrix or maybe stackoverflow is a good place to ask.

**Comment by mprekr** [comment]
Dear Jesse,

I will try what you sugested. Have a pleasant day.


kind regards
mprekr

2018-04-30 16:15 GMT+02:00 Jesse <notifications@github.com>:

**Comment by mprekr** [comment]
Dear Jesse,

I went with my issue public on github becasue I think that will make it
faster. I am just checking the solutions that you have given to me. Have a
pleasant day.


kind regards
mprekr

2018-05-01 12:48 GMT+02:00 MP PM <mprekr@gmail.com>:

**Comment by mprekr** [comment]
Dear Jesse,

Thank you once more for your valuable input I solved the most issues that I
had with my code and I am proceeding with it.





kind regards
mprekr
