### ISSUE TITLE
1.5 Version crypto2xts cran

### ISSUE THREAD

**Issue by izk8** [JesseVent/crypto#16]
Using the `install.packages("crypto", dependencies = TRUE)
`resulted in getting the older version of crypto and therefore I got the error `could not find function "crypto2xts"`. 

## Context

I did a couple things but obviously using `devtools::install_github("jessevent/crypto")` and then also restarting R seemed to fix it.

**Comment by JesseVent** [comment]
Yeah this was because I hadn't resubmitted latest Github changes to CRAN yet. I've submitted them now so should be updated on CRAN in a day or two.
