### ISSUE TITLE
Data inconsistency

### ISSUE THREAD

**Issue by BenasBiz** [JesseVent/crypto#19]
## Detailed Description

First of all, thanks for the great open source tool!
I have been using it for crypto market analysis for almost three months now. However, there are inconsistencies in the data. Because of them, I cannot use the full potential of the data.
There are two types of inconsistencies:
(1) Some data entries are simply missing (i.e. first half of January 2018 and April 2018);
(2) The 20th day of each month (both past and future) are repeated multiple times (1 entry is correct and the other 1-2 rows are just random numbers)

## Context

I believe this change is very important not only to me, but also to all crypto analysts. This would allow to analyse ant interpret the data correctly.

## Possible Implementation

I am sorry, but I am not a developer, thus cannot really suggest ideas for fixes...

## Your Environment

* Version used: 1.6
* Environment name and version (e.g. Chrome 39, node.js 5.4): Rstudio
* Operating System and version (desktop or mobile): Windows 8
* Link to your project:

**Comment by JesseVent** [comment]
Can you provide any specific examples of impacted tokens where it’s missing or repeated?

**Comment by BenasBiz** [comment]
This screenshot shows both problems.
![image](https://user-images.githubusercontent.com/35103190/40476475-c8c5965e-5f4c-11e8-9837-e22044c7b0e7.png)

**Comment by JesseVent** [comment]
<img width="835" alt="screen" src="https://user-images.githubusercontent.com/16379819/40481979-49e5dfce-5f92-11e8-8a06-f209eb2adfc3.png">

This is my raw output directly from R.
I can't replicate the same issue, maybe its a formatting thing with excel. I also created a [kernel on kaggle to unit test the data](https://www.kaggle.com/jessevent/crypto-data-unit-testing) directly.

**Comment by BenasBiz** [comment]
This is the code lines and raw output I get in R.
Maybe I input the wrong code?
![image](https://user-images.githubusercontent.com/35103190/40529178-606d8840-5ffc-11e8-82d3-c2f18d33b997.png)

**Comment by JesseVent** [comment]
Man thats so weird, it looks like its filtering out some of the result set somewhere. Can you try running `print(sessionInfo())` after loading the package and see what it outputs? I wonder if its missing something on windows.

```R
> print(sessionInfo())
R version 3.5.0 (2018-04-23)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.4

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] crypto_0.1.7  rvest_0.3.2   xml2_1.2.0    foreach_1.4.4

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.17     bindr_0.1.1      magrittr_1.5    
 [4] tidyselect_0.2.4 lattice_0.20-35  R6_2.2.2        
 [7] rlang_0.2.0      stringr_1.3.1    httr_1.3.1      
[10] dplyr_0.7.5      xts_0.10-2       tools_3.5.0     
[13] parallel_3.5.0   grid_3.5.0       snow_0.4-2      
[16] iterators_1.0.9  yaml_2.1.19      assertthat_0.2.0
[19] tibble_1.4.2     doSNOW_1.0.16    bindrcpp_0.2.2  
[22] purrr_0.2.4      tidyr_0.8.1      codetools_0.2-15
[25] glue_1.2.0       stringi_1.2.2    compiler_3.5.0  
[28] pillar_1.2.2     jsonlite_1.5     lubridate_1.7.4 
[31] zoo_1.8-1        pkgconfig_2.0.1 
```

**Comment by JesseVent** [comment]
I also cleaned up a version of the getCoins function to see if we can isolate where the datas getting weird, unfortunately i'm unable to test on a windows machine.

 If we compare `results_data, results and marketdata` objects from the below script it should give us a pretty good basis to try narrow down the issue.

```R
library(crypto)
options(scipen = 999)

# Parameters
coin       <- NULL
start_date <- "20171231"
end_date   <- NULL

coins     <- crypto::listCoins(coin, start_date, end_date)
coinnames <-
  dplyr::data_frame(
    symbol = as.character(coins$symbol),
    name   = as.character(coins$name),
    rank   = coins$rank,
    slug   = coins$slug
  )
length    <- as.numeric(length(coins$history_url))
zrange    <- 1:as.numeric(length(coins$history_url))
cpu_cores <- as.numeric(parallel::detectCores(all.tests = FALSE, logical = TRUE))
cluster   <- parallel::makeCluster(cpu_cores, type = "SOCK")

doSNOW::registerDoSNOW(cluster)
pb           <- txtProgressBar(max = length, style = 3)
progress     <- function(n) setTxtProgressBar(pb, n)
opts         <- list(progress = progress)
attributes   <- coins$history_url
slug         <- coins$slug
results_data <- foreach::foreach(
  i              = zrange,
  .errorhandling = c('remove'),
  .options.snow  = opts,
  .combine       = rbind,
  .verbose       = FALSE
) %dopar% crypto::scraper(attributes[i], slug[i])
close(pb)
parallel::stopCluster(cluster)

results    <- merge(results_data, coinnames, by = "slug")
marketdata <- results %>% as.data.frame()
colnames(marketdata) <- c("slug", "date", "open", "high", "low", "close", "volume", "market", "symbol", "name", "ranknow")
marketdata <- marketdata[c("slug", "symbol", "name", "date", "ranknow", "open", "high", "low", "close", "volume", "market")]

# Curious if the data looks right up until this point
marketdata$date     <- suppressWarnings(lubridate::mdy(unlist(marketdata$date)))

# Or if it changes after running one of these
cols                <- c(5:11)
ccols               <- c(7:11)
marketdata[, cols]  <- apply(marketdata[, cols], 2, function(x) gsub(",", "", x))
marketdata[, ccols] <- apply(marketdata[, ccols], 2, function(x) gsub("-", "0", x))
marketdata$volume   <- marketdata$volume  %>% tidyr::replace_na(0) %>% as.numeric()
marketdata$market   <- marketdata$market  %>% tidyr::replace_na(0) %>% as.numeric()
marketdata[, cols]  <- suppressWarnings(apply(marketdata[, cols], 2, function(x) as.numeric(x)))
marketdata          <- na.omit(marketdata)
results             <- marketdata[order(marketdata$ranknow, marketdata$date, decreasing = FALSE), ]
```

**Comment by BenasBiz** [comment]
This is what I get after running `print(sessionInf())`
`> print(sessionInfo())
R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Lithuanian_Lithuania.1257  LC_CTYPE=Lithuanian_Lithuania.1257    LC_MONETARY=Lithuanian_Lithuania.1257 LC_NUMERIC=C                          LC_TIME=Lithuanian_Lithuania.1257    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_2.2.1 crypto_0.1.7  rvest_0.3.2   xml2_1.2.0    foreach_1.4.4

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.16     pillar_1.2.1     compiler_3.5.0   plyr_1.8.4       bindr_0.1.1      iterators_1.0.9  xts_0.10-2       tools_3.5.0      lubridate_1.7.4  jsonlite_1.5     tibble_1.4.2    
[12] gtable_0.2.0     lattice_0.20-35  pkgconfig_2.0.1  doSNOW_1.0.16    rlang_0.2.0      parallel_3.5.0   bindrcpp_0.2.2   dplyr_0.7.4      httr_1.3.1       stringr_1.3.0    grid_3.5.0      
[23] glue_1.2.0       R6_2.2.2         snow_0.4-2       tidyr_0.8.0      purrr_0.2.4      magrittr_1.5     scales_0.5.0     codetools_0.2-15 assertthat_0.2.0 colorspace_1.3-2 stringi_1.1.7   
[34] lazyeval_0.2.1   munsell_0.4.3    zoo_1.8-1       
> `

**Comment by BenasBiz** [comment]
Hi,
It worked! All the data now is consistent:
![image](https://user-images.githubusercontent.com/35103190/40607103-2af527ec-6270-11e8-865b-b259236fb7bb.png)

What was ultimately the problem?

**Comment by JesseVent** [comment]
Great news! 

When calling the function it must expect the data encoding to be UTF-8, and if it has a locale set that uses a different encoding to UTF-8 then it messes up because it reads characters and dates in differently. In this case it was converting the dates incorrectly. 

It’s a good thing to know though, thanks for your help, I would of never identified this as an issue otherwise. I might release a new version where it gets your existing locale, then enforces UTF-8, then swaps back again so you don’t need to do it manually.

**Comment by JesseVent** [comment]
I've uploaded the latest version onto github now, you should be able to install it by running the below. Please run it and let me know how you go, I've included the locale fix but have been unable to test it.

```R
install.packages(devtools)
devtools::install_github("jessevent/crypto")
```

**Comment by BenasBiz** [comment]
Throws an error:
![image](https://user-images.githubusercontent.com/35103190/40621838-57a29c48-62a7-11e8-8b66-8d9b5d63624e.png)

**Comment by JesseVent** [comment]
Ahh the issues with windows and devtools...

I've submitted to CRAN, you could probably install from directly from their file or wait until its on the proper repository.

[CRAN win-builder crypto_1.0.0.zip](https://win-builder.r-project.org/nJgAFzn14Xf3/crypto_1.0.0.zip)

**Comment by BenasBiz** [comment]
What exactly should I do with this .zip file? 
I extracted its whole content to RStudio directory on disk C and tried to run RStudio again, but got the same error message.

**Comment by JesseVent** [comment]
I got an email 20 minutes ago saying the latest version is approved and deployed to CRAN. Probably will just take a few hours before it appears on the different repositories but i'd just wait and install it that way.

**Comment by BenasBiz** [comment]
What should I attempt to do exactly?

What is CRAN exactly and what should I do with it/in it?

Pardon me for my technical incompetence...

**Comment by JesseVent** [comment]
CRAN stands for the 'Comprehensive R Archive Network', they manually verify R packages that get submitted to the repository and are screened before going through an approval process. Using published packages from CRAN is probably the 'most formal' way you can access other peoples code with R.

Benefits of being in CRAN is there are base functions in R that use their repository, simply by calling `install.packages("crypto", dependencies = TRUE)` or by using the GUI in R-Studio to install them.

**Comment by BenasBiz** [comment]
I think it worked with running `install.packages("devtools")` and then `devtools::install_github("jessevent/crypto")`. This is what I got:

```R
> install.packages("devtools")
also installing the dependencies ‘memoise’, ‘whisker’, ‘rstudioapi’, ‘git2r’, ‘withr’
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/memoise_1.1.0.zip'

Content type 'application/zip' length 36421 bytes (35 KB)
downloaded 35 KB
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/whisker_0.3-2.zip'

Content type 'application/zip' length 80908 bytes (79 KB)
downloaded 79 KB
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/rstudioapi_0.7.zip'

Content type 'application/zip' length 147168 bytes (143 KB)
downloaded 143 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/git2r_0.21.0.zip'
Content type 'application/zip' length 3098045 bytes (3.0 MB)
downloaded 3.0 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/withr_2.1.2.zip'
Content type 'application/zip' length 150344 bytes (146 KB)
downloaded 146 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/devtools_1.13.5.zip'
Content type 'application/zip' length 701514 bytes (685 KB)
downloaded 685 KB

package ‘memoise’ successfully unpacked and MD5 sums checked
package ‘whisker’ successfully unpacked and MD5 sums checked
package ‘rstudioapi’ successfully unpacked and MD5 sums checked
package ‘git2r’ successfully unpacked and MD5 sums checked
package ‘withr’ successfully unpacked and MD5 sums checked
package ‘devtools’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\benasbiz\AppData\Local\Temp\RtmpmmnaCD\downloaded_packages
> devtools::install_github("jessevent/crypto")
Downloading GitHub repo jessevent/crypto@master
from URL https://api.github.com/repos/jessevent/crypto/zipball/master
Installing crypto
Installing 1 package: dplyr
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/dplyr_0.7.5.zip'
Content type 'application/zip' length 3048145 bytes (2.9 MB)
downloaded 2.9 MB

package ‘dplyr’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\benasbiz\AppData\Local\Temp\RtmpmmnaCD\downloaded_packages
Installing 1 package: tidyr
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/tidyr_0.8.1.zip'
Content type 'application/zip' length 943666 bytes (921 KB)
downloaded 921 KB

package ‘tidyr’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\benasbiz\AppData\Local\Temp\RtmpmmnaCD\downloaded_packages
"C:/Users/benasbiz/DOCUME~1/Crypto/5-FUND~1/Data/R-35~1.0/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/benasbiz/AppData/Local/Temp/RtmpmmnaCD/devtools11887656316/JesseVent-crypto-15a8829" --library="C:/Users/benasbiz/Documents/Crypto/5-Fundamentals/Data/R-3.5.0/library"  \
  --install-tests 

* installing *source* package 'crypto' ...
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'crypto'
    finding HTML links ... done
    crypto2xts                              html  
    daily_market                            html  
    getCoins                                html  
    getExchanges                            html  
    getPrices                               html  
    global_market                           html  
    listCoins                               html  
    repair_dependencies                     html  
    replace_encoding                        html  
    reset_encoding                          html  
    scraper                                 html  
** building package indices
** testing if installed package can be loaded
* DONE (crypto)
In R CMD INSTALL
```

So I think it all worked.
But now when I try to run `getcoins()`, it does not allow me to add a start date to the formula.

**Comment by JesseVent** [comment]
Ahhh you can ignore that, I accidentally just left the verbose mode on. Shouldn't impact anything

**Comment by JesseVent** [comment]
I'm glad this works though!
```R
Warning: Changing locale encoding from Lithuanian_Lithuania.1257  to UTF-8. Post completion locale will be reset to Lithuanian_Lithuania.1257
```

**Comment by BenasBiz** [comment]
So now I don't have to run 'install.package("devtools")' and 'install.package("crypto")' or I still have to run these before running getcoins?

**Comment by JesseVent** [comment]
Nah you no longer need to install devtools, and `install.packages("crypto")` will just update it to latest version - I resubmitted fix to resolve issue with verbose mode

**Comment by BenasBiz** [comment]
Perfect, thanks! If anything else happens, will let you know.
