### ISSUE TITLE
Data not downloaded anymore

### ISSUE THREAD

**Issue by Gringooooo** [JesseVent/crypto#21]
Hi Jesse,
Second time that I contact you concerning this tool, again, first thing, thank you very much.
I have just updated R, Rstudio and the various packages, and I cannot load data anymore.
I have attached a screenshot below with the session infos and also the message I receive when I launch Crypto History. I understand that you have automatized the encoding mode, I don’t know if it is related to that but now data are not downloaded anymore.
My R stays as it is on screenshot with the blinking cursor and no info about the download.
Many thanks again, and I hope it is just a small glitch.
G

## Your Environment
My Print Session is included on the attached screenshot.

![j](https://user-images.githubusercontent.com/37179342/40980889-d4354d86-68d9-11e8-8d51-771f2b647a5d.PNG)

**Comment by Gringooooo** [comment]
PS: additional informations:

During my first reinstallation I have installed the crypto lib directly from Github.

I just made a new fresh install of R, Rstudio and the crypto lib, but this time from Cran and I have the same issue.

**Comment by JesseVent** [comment]
Hi Gringo, I just deployed a fix I think will work to github, can you please install `devtools::install_github("jessevent/crypto")` and try again. 

I added an additional check in  the encoding function to see if you already have UTF-8 for windows, and if you do then don't make any changes.. Hopefully it resolves the issue you're experiencing.

Thanks

**Comment by Gringooooo** [comment]
Hi Jesse,
I just did it but unfortunately R is not loading (downloading?) anything.

Here is the screenshot when I launch Crypto History, nothing occur:
![sc_a](https://user-images.githubusercontent.com/37179342/41041237-d2e542b8-699e-11e8-87d2-1b80a9976cb1.png)

Here my new Print Session: nothing sounds anormal:
![sc_b](https://user-images.githubusercontent.com/37179342/41041271-e632fe46-699e-11e8-8686-137984957a5b.png)

**Comment by Gringooooo** [comment]
I just did it and here the result:
![scc](https://user-images.githubusercontent.com/37179342/41046671-15521430-69ab-11e8-9e2b-35924076ab87.png)

**Comment by JesseVent** [comment]
Does running the main function work now?

**Comment by Gringooooo** [comment]
Hi,
Still not working, I really don't know if the issue is on my side or if CMC is changing stuff to avoid downloading....

Here the new message after updating the tool:
![sc](https://user-images.githubusercontent.com/37179342/41088140-ff7a0c14-6a3e-11e8-9949-8efbadc00aaf.png)

**Comment by Gringooooo** [comment]
And here my new session info:

![sc](https://user-images.githubusercontent.com/37179342/41088217-39b6ce62-6a3f-11e8-91e5-8ce91714aae6.png)

**Comment by JesseVent** [comment]
That URL is still valid, are you connecting through a proxy or anything?

The below is a cleaned up script version of the crypto_history function - i'm hoping when you run this it isolates where its breaking for you..

```R
library(crypto)

# Parameters
coin       <- NULL
start_date <- "20171231"
end_date   <- NULL


options(scipen = 999)
sys_locale <- Sys.getlocale(category = "LC_TIME")
replace_encoding(sys_locale)

coins     <- crypto::crypto_list(coin, start_date, end_date)
coinnames <-
  dplyr::data_frame(
    symbol = as.character(coins$symbol),
    name   = as.character(coins$name),
    rank   = coins$rank,
    slug   = coins$slug
  )
length    <- as.numeric(length(coins$history_url))
zrange    <- 1:as.numeric(length(coins$history_url))
cpu_cores <- as.numeric(parallel::detectCores(all.tests = FALSE, logical = TRUE))
cluster   <- parallel::makeCluster(cpu_cores, type = "SOCK")

doSNOW::registerDoSNOW(cluster)
pb           <- txtProgressBar(max = length, style = 3)
progress     <- function(n) setTxtProgressBar(pb, n)
opts         <- list(progress = progress)
attributes   <- coins$history_url
slug         <- coins$slug
results_data <- foreach::foreach(
  i              = zrange,
  .errorhandling = c('remove'),
  .options.snow  = opts,
  .combine       = rbind,
  .verbose       = TRUE
) %dopar% crypto::scraper(attributes[i], slug[i])
close(pb)
parallel::stopCluster(cluster)

results    <- merge(results_data, coinnames, by = "slug")
marketdata <- results %>% as.data.frame()
colnames(marketdata) <- c("slug", "date", "open", "high", "low", "close", "volume", "market", "symbol", "name", "ranknow")
marketdata <- marketdata[c("slug", "symbol", "name", "date", "ranknow", "open", "high", "low", "close", "volume", "market")]
marketdata$date     <- suppressWarnings(lubridate::mdy(unlist(marketdata$date)))

cols                <- c(5:11)
ccols               <- c(7:11)
marketdata[, cols]  <- apply(marketdata[, cols], 2, function(x) gsub(",", "", x))
marketdata[, ccols] <- apply(marketdata[, ccols], 2, function(x) gsub("-", "0", x))
marketdata$volume   <- marketdata$volume  %>% tidyr::replace_na(0) %>% as.numeric()
marketdata$market   <- marketdata$market  %>% tidyr::replace_na(0) %>% as.numeric()
marketdata[, cols]  <- suppressWarnings(apply(marketdata[, cols], 2, function(x) as.numeric(x)))
marketdata          <- na.omit(marketdata)
results             <- marketdata[order(marketdata$ranknow, marketdata$date, decreasing = FALSE), ]
```

**Comment by Gringooooo** [comment]
Usually I am connecting with a VPN. 

For the test bellow I am not using any VPN or other stuff and here where is stops:

![sc](https://user-images.githubusercontent.com/37179342/41100216-11e43f7e-6a61-11e8-9577-d3f8541fddf1.png)

**Comment by Gringooooo** [comment]
Maybe I shouldn't have updated R to the latest version, it was working fine with the older version, but as my version was already a few month old, I wanted to update everything to make sure everything continue to works...

**Comment by Gringooooo** [comment]
PS: I should add that I am running the script at a client place, I will try from my home connection later today to confirm.

**Comment by JesseVent** [comment]
Looks like the issue is definitely with your parallel processing or windows firewall not allowing R to allow external connections to the clusters.

In the below script I changed the function to a more windows friendly type of cluster creation just to see if that works.

Either way, I just deployed a change to GitHub to completely bypass all parallel processing functions when you explicitly set the parameter `cpu_cores=1`. This won't present a loading bar but will display a message saying it will take some time to run.. Pretty much all I can do to assist if it's a parallel processing issue.


```R
library(crypto)

# Parameters
coin       <- NULL
start_date <- "20171231"
end_date   <- NULL

options(scipen = 999)
sys_locale <- Sys.getlocale(category = "LC_TIME")
replace_encoding(sys_locale)

coins     <- crypto::crypto_list(coin, start_date, end_date)
coinnames <-
  dplyr::data_frame(
    symbol = as.character(coins$symbol),
    name   = as.character(coins$name),
    rank   = coins$rank,
    slug   = coins$slug
  )
length    <- as.numeric(length(coins$history_url))
zrange    <- 1:as.numeric(length(coins$history_url))
cpu_cores <- as.numeric(parallel::detectCores(all.tests = FALSE, logical = TRUE))

#cluster   <- parallel::makeCluster(cpu_cores, type = "SOCK")
# doSNOW::registerDoSNOW(cluster)

cluster <- makePSOCKcluster(cpu_cores)
doParallel::registerDoParallel(cluster)

pb           <- txtProgressBar(max = length, style = 3)
progress     <- function(n) setTxtProgressBar(pb, n)
opts         <- list(progress = progress)
attributes   <- coins$history_url
slug         <- coins$slug
results_data <- foreach::foreach(
  i              = zrange,
  .errorhandling = c('remove'),
  .options.snow  = opts,
  .combine       = rbind,
  .verbose       = TRUE
) %dopar% crypto::scraper(attributes[i], slug[i])
close(pb)

#parallel::stopCluster(cluster)
doParallel::stopImplicitCluster(cluster)
```

**Comment by Gringooooo** [comment]
Many thanks for helping me, I just tried your last script (I just add "bitcoin" in coin to limit the download to 1 coin) and it has downloaded it:

I will try from home in 2 hours time to see the outcome.

Screenshot 1:
![sca](https://user-images.githubusercontent.com/37179342/41104075-e31aa412-6a6a-11e8-9c07-229e829460d1.png)
Screenshot 2:
![scb](https://user-images.githubusercontent.com/37179342/41104100-edbbd3aa-6a6a-11e8-8b11-f464f92c0cfd.png)

**Comment by Gringooooo** [comment]
Hi,
To clarify, I performed those tests on my laptop which is a Mac Book Pro Retina running with Windows 10 directly installed on it (not parallel).

Latest R version 3.5 with latest Crypto lib:
============================================
When I use your latest mod (cpu_cores=1) it is working. As you said I cannot see the loading bar but at the end after a while the data are downloaded.

Previous install R 3.4.3 and Crypto lib 0.1.5
============================================
Everything was working fine, I was seeing the loading bar.

Is there any reason why everything was working fine in my previous installation and not in the new one.

Could it be because of the new R version or is there any reason related to the crypto lib which work differently in the latest updates?

I am going to perform a test on my VPS which is running on Windows server 2012 to see the outcome.

**Comment by JesseVent** [comment]
I’m not sure what would of changed, maybe raise a ticket against the parallel package

One thing they changed recently was the ability to set a random port for the cluster.

My last recommendation would be to try this
`Sys.setenv("R_PARALLEL_PORT"="random")`

**Comment by Gringooooo** [comment]
Hi,
To clarify, I performed those tests on my laptop which is a Mac Book Pro Retina running with Windows 10 directly installed on it (not parallel).

Latest R version 3.5 with latest Crypto lib:
============================================
When I use your latest mod (cpu_cores=1) it is working. As you said I cannot see the loading bar but at the end after a while the data are downloaded.

Previous install R 3.4.3 and Crypto lib 0.1.5
============================================
Everything was working fine, I was seeing the loading bar.

Is there any reason why everything was working fine in my previous installation and not in the new one.

Could it be because of the new R version or is there any reason related to the crypto lib which work differently in the latest updates?

I am going to perform a test on my VPS which is running on Windows server 2012 to see the outcome.
