### ISSUE TITLE
daily_market('BTG') bug

### ISSUE THREAD

**Issue by DuyDD** [JesseVent/crypto#23]
## Detailed Description

<! daily_market('BTG') returns an error -->

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by JesseVent** [comment]
That occurs because "BTG" isn’t a unique symbol and there’s another token that has the same symbol name. If you used the slug or full name it would successfully return bitcoin-gold

**Comment by DuyDD** [comment]
Ah, I see. Thanks!

**Comment by DuyDD** [comment]
Hi Jesse,

I'm now having trouble with the daily_market() function again. I'm noticing
the issue for R version 3.5.1 but not for R version 3.4.4.

daily_market('icon')
lexical error: invalid char in json text. ...

Using either the name or the slug, there was this issue. Have you noticed
this issue?

Best,
Duy

**Comment by JesseVent** [comment]
Same issue, 

daily_market('icon') cant select icon or iconic
```r
"https://graphs2.coinmarketcap.com/currencies/icon\nhttps://graphs2.coinmarketcap.com/currencies/iconic"

coins
       name symbol rank   slug               tokens   id
35     ICON    ICX   35   icon      ICON, icon, ICX 2099
1627 Iconic   ICON 1627 iconic Iconic, iconic, ICON 1528
```

This works `daily_market('icx')`

**Comment by DuyDD** [comment]
Ah I see. Thanks :-)
