### ISSUE TITLE
Coinmarketcap changed table layout

### ISSUE THREAD

**Issue by yailya** [JesseVent/crypto#24]
Seems like coinmarketcap has changed the layout of the markets page so there are several new columns in the table available. It affects the way function crypto_exchanges() works. 

## Possible Implementation
the only snippet that needs to be updated is the list of columns headers -->colnames
here is the working code

  colnames(exchangedata) <-
    c(
      "slug",
      "exchange_rank",
      "exchange_name",
      "trading_pair",
      "exchange_volume",
      "exchange_price",
      "exchange_share",
      "category",
      "fee_type",
      "last_updated",
      "symbol",
      "name",
      "coin_rank"
    )
PS thanks a lot for buiding such a usefull lib

**Comment by JesseVent** [comment]
Thanks for letting me know, this should be fixed with latest commit https://github.com/JesseVent/crypto/commit/748e2f3dbd99521bdb032c3c9ec3ea3c318dd618
