### ISSUE TITLE
Column names meaning

### ISSUE THREAD

**Issue by waynelapierre** [JesseVent/crypto#26]
I use the crypto pakcage to retrieve historical crypto data. I am not sure about the column names meaning. Specifically, is the column 'volume' in shares or dollars?  The values are all integers, so I am guessing it is in shares. Also, what does the column 'market' and 'close ratio' mean?

**Comment by JesseVent** [comment]
All the values are in US dollars, Volume the volume in USD traded.

For more details around the format I would recommending viewing the raw data at [Coin market caps historic prices](https://coinmarketcap.com/currencies/bitcoin/historical-data/), or their FAQ page which talks about how they calculate it.

### Market 

Market Cap = Price X Circulating Supply

### Close Ratio

As for close ratio, imagine you have a scale between the Lowest point for that day, and the highest point and want to know where it closed that day in comparison to high and low points. The logic is as follows: `CLOSE_RATE = (close - low) / (high - low)`

Take example the following diagrams where CLOSE_RATE = X

`low= 1, high=2, close=1.5`

LOWEST <--------------------------------------X--------------------------------------> HIGHEST

> Answer: CLOSE_RATE IS EQUAL TO 0.50

close_rate is the normalised (between 0 - 1) value to represent X in the above diagram and is worked out as follows.
```
  CLOSE_RATE = (1.5 - 1) / (2 - 1)
  CLOSE_RATE = (0.5) / (1)
  CLOSE_RATE = 0.5
```


`low= 1, high=2, close=1.75`

LOWEST <---------------------------------------------------------X-------------------> HIGHEST

> Answer: CLOSE_RATE is equal to 0.75

`low= 1, high=2, close=1.25`

LOWEST <-------------------X---------------------------------------------------------> HIGHEST

> Answer: CLOSE_RATE is equal to 0.25

Hope that helps clarify
