### ISSUE TITLE
Trouble with crypto_exchanges function

### ISSUE THREAD

**Issue by KCostaREAL** [JesseVent/crypto#27]
I am having issues with the crypto_exchanges function on my Mac running 10.11.6. I simply want to retrieve the exchange information for all ETH markets. The code I used was 

library(crypto)
coin <- "eth"
ETH_Exchanges <- crypto_exchanges(coin)

and I get an output of 21 obs. of 11 variables:
![image](https://user-images.githubusercontent.com/43416903/45767212-2fee4880-bbff-11e8-89db-51fbaa1f15e1.png)

I must be doing something wrong, no? Thank you for developing such a useful library, I love it.

**Comment by JesseVent** [comment]
Hi, this should be fixed on the GitHub version, but not yet uploaded to CRAN.

Try `devtools::install_github("jessevent/crypto")` and let me know if that resolves the issue

**Comment by JesseVent** [comment]
I worked out this was actually something else, I’ve fixed it and it’s now on CRAN
