### ISSUE TITLE
Additional Package Dependencies - snow, doSNOW

### ISSUE THREAD

**Issue by tacuba** [JesseVent/crypto#3]
The current Prerequisites section lists foreach, rvest, xml2 as high level dependencies.

I just did a fresh install of R 3.4.3 and noticed that the getCoins() function fails to execute unless 'snow' and 'doSNOW' are loaded.  Suggest updating the README to include these dependencies.

Thanks for your work on this package!

**Comment by JesseVent** [comment]
Updated readme, also this package is now available on the CRAN repository, so hopefully should install doSNOW as a dependency
