### ISSUE TITLE
Inconsistent and incomplete results from getCoins() and crypto_history()

### ISSUE THREAD

**Issue by thelmmortal1** [JesseVent/crypto#33]
getCoins() and crypto_history() are not working as they used to. 

1. The basic getCoins() or crypto_history() ARE NOT pulling all coins for their entire history
--It is only pulling anywhere between 10-50 coins at a time, and the particular coins are not consistent
--As in I can run getCoins() now and in 15 minutes I can run it again and get a totally different result

2. The same problem in #1 occurs whether I set a particular start date. I simply am only getting 10-50 coins at a time, but this time with less history. 

3. The limit functionality is also not working as intended. I'm getting similar results as #1 and #2 issues above.

4. As mentioned previously I can run the exact same code and get totally different results...but I am also getting a result of "Error: No data currently exists for this cryptocurrency that can be scraped."

5. However if I identify the particular coin I want it to return getCoins('PRL') as an example, it still works 100% as intended. Beautiful. Same with crypto_history('PRL')

Attached is the basic run of:

all_coins <- getCoins()

As you can see I am not getting anywhere near all the coins at this point.

[all_coins_forJV.txt](https://github.com/JesseVent/crypto/files/2522372/all_coins_forJV.txt)

6. Last semi related ?....with CMC going to their professional API. How is that going to impact this package?

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by ProcessP** [comment]
I am having the same issue.

**Comment by JesseVent** [comment]
It appears coinmarketcap have now implemented a rate limiter, when debugging I received the following error message after 30 calls.

`Error in open.connection(x, "rb") : HTTP error 429.`

Looks like they've updated their API documentation to include the following..

```
Limits
Please limit requests to no more than 30 per minute.
Endpoints update every 5 minutes.
```

For now I've put a fix to accommodate the rate limiter in the scraper function, but it will take a fair bit longer to retrieve results. Please install latest development version through `devtools::install_github("JesseVent/crypto")` and let me know how you go.

As for when they release the professional API version I am still thinking on how best to handle that, as I think I will need to provide the ability for users to add their own API key when calling the service, other than that it doesn't look that different. Appreciate any thoughts or ideas.

```R
> library(crypto)
Loading required package: foreach
Loading required package: rvest
Loading required package: xml2

> df <- crypto_history(limit = 50)

   user  system elapsed 
  0.475   0.367 129.815 

> length(unique(df$slug))
[1] 50
```

**Comment by thelmmortal1** [comment]
I'm still getting an error. I ran getCoins for amount 4 months of data.

This is what I'm getting....  I'm going to run getCoins just for the last couple days, maybe that'll work

  |================================================================================                                                                          |  52%error calling combine function:
<Rcpp::exception in bind_rows_(x, .id): Column `Volume` can't be converted from character to integer>
  |========================================================================================                                                                  |  57%error calling combine function:
<Rcpp::exception in bind_rows_(x, .id): Column `Volume` can't be converted from character to integer>
  |=======================================================================================================                                                   |  67%error calling combine function:
<Rcpp::exception in bind_rows_(x, .id): Column `Volume` can't be converted from character to integer>
  |===============================================================================================================                                           |  72%error calling combine function:
<Rcpp::exception in bind_rows_(x, .id): Column `Open*` can't be converted from numeric to character>
error calling combine function:
<Rcpp::exception in bind_rows_(x, .id): Column `Volume` can't be converted from character to integer>
  |================================================================================================================                                          |  73%error calling combine function:
<Rcpp::exception in bind_rows_(x, .id): Column `Volume` can't be converted from character to integer>
  |=================================================================================================================                                         |  73%error calling combine function:
<Rcpp::exception in bind_rows_(x, .id): Column `Volume` can't be converted from character to integer>
error calling combine function:
<Rcpp::exception in bind_rows_(x, .id): Column `Volume` can't be converted from character to integer>

**Comment by thelmmortal1** [comment]
Same problem as my previous comment when I use crypto_history and I set the start date to return only 1 days worth of returns.

I am NOT setting a limit though (if that may be a problem). I'm hoping to return results from all coins (at least the top 400-500). 

Thanks for all you do. If I ever make money I'll be sure to send you a big tip :)

**Comment by JesseVent** [comment]
Hmm maybe make sure you’ve loaded the dplyr package before hand that might help. The number of days shouldn’t matter it’s more likely the number of coins

**Comment by tmlee** [comment]
Hey guys, you might want to check out or consider our public open API at http://coingecko.com/api
It's aimed to be easy to consume and lenient with limits.

Happy to answer any questions you might have and how we can help

**Comment by thelmmortal1** [comment]
Still getting some problems Jesse.

It seems like I am hitting the rate limiter still. For example if I set it at a limit of 500 I'll get a bunch of coins, then I'll have a gap of 30 or 31 coins....then I'll get a bunch more coins...then another gap of 30-31 coins...and some more coins and then another gap...

^^^^ Is happening whether or not I set a low limit, high limit, or no limit



Also it seems I ONLY get the following error when I set no limit or if I set a really high limit (like >1000)

|================================================================================================================= | 73%error calling combine function:
<Rcpp::exception in bind_rows_(x, .id): Column Volume can't be converted from character to integer>
error calling combine function:
<Rcpp::exception in bind_rows_(x, .id): Column Volume can't be converted from character to integer>

**Comment by JesseVent** [comment]
Can you run `parallel::detectCores(all.tests = FALSE, logical = TRUE)` and run `parallel::detectCores(all.tests = FALSE, logical = FALSE)` and let me know the results? Your system could be running multiple threads per CPU which could cause the discrepancy. 

I’ll commit a tweak to the delay for the rate limiter so let me know how that goes.

**Comment by JesseVent** [comment]
@tmlee very interesting, I’ll look into this thanks

**Comment by thelmmortal1** [comment]
It has been inconsistent recently. I haven't tried running with no coin # limitation, but limits around 500 coins have been hit and miss. Sometimes it works like a charm, and sometimes roughly 1/3-1/2 the coins get kicked out.

**Comment by JesseVent** [comment]
Did the latest commit with the tweak help? `devtools::install_github("jessevent/crypto")`

**Comment by JesseVent** [comment]
I've made pretty big changes to how it handles it, and working for me on 800 coins. My internet gets a fair bit of dropouts hence the 797.

```R
devtools::install_github("jessevent/crypto")
library(crypto)

coins <- getCoins(limit = 800)
#  |===============================================================| 100%
#    user   system  elapsed 
#  23.384   13.247 3831.134 
length(unique(coins$slug))
# [1] 797
```
