### ISSUE TITLE
error when loading library(crypto), 

### ISSUE THREAD

**Issue by samotleriche** [JesseVent/crypto#36]
when I use library(crypto) i get an error.

## Detailed Description

This error is as follows: 

Error: package or namespace load failed for ‘crypto’:
 object ‘askForSecret’ is not exported by 'namespace:rstudioapi'

any idea how to fix this?

I apologize is this isn't the right place to ask such a question.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by JesseVent** [comment]
It’s just a dependency on the rstudioapi package, this link has a really good guide on setting it up.

https://support.rstudio.com/hc/en-us/articles/360000969634-Using-Keyring

**Comment by MR1991** [comment]
After installing rstudioapi I get following error when trying to install crypto package±
Error : object ‘askYesNo’ is not exported by 'namespace:utils'
Utils is a base package though. Any ideas? Im using R 3.4.4

**Comment by JesseVent** [comment]
Ahhh that function was introduced in 3.5, I was trying to make it backwards compatible and not require it, I’ll reevaluate and fix tonight.

**Comment by JesseVent** [comment]
Removed function call for askYesNo so should work for 3.4x versions of R now
