### ISSUE TITLE
Error in Sys.setlocale("LC_TIME", locale)

### ISSUE THREAD

**Issue by ProcessP** [JesseVent/crypto#38]
I am getting the following errors 
```
Error in Sys.setlocale("LC_TIME", locale) : 
  (converted from warning) OS reports request to set locale to "en_US.UTF-8" cannot be honored
In addition: Warning message:
In Sys.setlocale("LC_TIME", locale) :
  OS reports request to set locale to "en_US.UTF-8" cannot be honored
```

I think it has something to do with the OS and the fact I am using windows

**Comment by JesseVent** [comment]
Could you please run the following code block and paste results

```R
install.packages("crypto")
library(crypto)
sessionInfo()
```

**Comment by JesseVent** [comment]
Does the issue still occur with version 1.1?

**Comment by PatRick2409** [comment]
I have the same problem with the newest R version. I also tried to set the local time to the required zone without success :/

**Comment by JesseVent** [comment]
I just made a change, can you please install latest version on GitHub through `devtools::install_github("jessevent/crypto")` and give that a try?  It should dynamically set the locale based on your platform now.

Please let me know how you go

**Comment by ProcessP** [comment]
Amazing. It works now!

________________________________

**Comment by JesseVent** [comment]
Glad to hear because the change is on CRAN now as version 1.1.1!
