### ISSUE TITLE
crypto_history skipping coins again

### ISSUE THREAD

**Issue by thelmmortal1** [JesseVent/crypto#39]
Similar problem as before. It has been off and on the past couple days (my internet is slower right now so maybe that is the problem?).

If I try to get a history of all the coins.. for example like this....

crypto_history(start_date = 20190220, limit = 200)

I'll get the first 20 ranked coins, then it'll skip a handful, then I'll get the next 10 or so, then it may skip some more... 

If I recall it had something to do with the rate limiter 

Also I want to again thank you for this package. It is amazing and you've done a tremendous job. Once crypto goes bull again you'll be getting a BIG tip from me!

**Comment by JesseVent** [comment]
Just had a quick look at found the following..  

# API Request Throttling
Use of the CoinMarketCap API is subject to API call rate limiting or "request throttling" that scales with the usage tier tied to your API Key. Free / Trial plans are limited to 10 API calls a minute. Paid subscription tiers are limited to 60 calls a minute and custom enterprise subscription tiers have higher limits. This limit resets every minute.

Looks like they’ve changed the rate limit from 30 to 10...

**Comment by thelmmortal1** [comment]
Wow, they are killing us! Well I guess slower is better than nothing at all. 

I don't have a key or anything like that. I just go straight through the package. So I'm guessing that points me on the 'free/trial' plan

Again, thanks for everything you've done.

**Comment by JesseVent** [comment]
When calling crypto_history you can pass the sleep parameter for the seconds to sleep between api requests, so for new rate limit use 6-7 seconds sleep. So could do `crypto_history(limit = 200, sleep = 7)` or something like that should do the job
