### ISSUE TITLE
Include historic data as .rda file

### ISSUE THREAD

**Issue by YsoSirius** [JesseVent/crypto#43]
I think it would be nice to have an initial dataset of all (or top 100) coins until a recent day, saved as dataset of this package, as the download of all coin histories can take quite some time. 
Then it would only be necessary to fill up that time gap, which should be much faster.

I have an .rda file of 40 different coins until the 24.06.2019 and thats about 1.2 MB and took several hours to download with `crypto_history()`. It might also be possible to upload that file on a public Dropbox account or similar, if the size of the data is too too big to include in a package.

I am not sure how many coins are available in total for historical data. Is it 2210 as the result of `crypto_list()` suggests?

**Comment by JesseVent** [comment]
I had been maintaining it every now and then on Kaggle, but the file just gets massive after a while. Will keep in mind for future though.
