### ISSUE TITLE
Coinmarketcap API deprecated, library no longer working

### ISSUE THREAD

**Issue by rsuhada** [JesseVent/crypto#46]
Queries return HTTP error 403, due to the deprecated API call.

## Possible Implementation
The new API does have a free plan. It requires an API key. I haven't looked through the documentation, whether the calls themselves changed...

[https://pro.coinmarketcap.com/features](url)

**Comment by JesseVent** [comment]
Queries using what function?

Theres already 3 options included in this package as to use the pro API, i'd suggest reading through the documentation.
