### ISSUE TITLE
[Feature Request] ability to download data between start and end dates

### ISSUE THREAD

**Issue by rexii2300** [JesseVent/crypto#7]
Found this to be immensely powerful in the analysis of crypto data. I've been trying to find a good API but stumbled across your package.

My aim is to have all my data in a sql database. Right now I can easily import the resulting dataframe into the database (using sqldf). The analysis can then be conducted in Power BI

An extremely useful feature would be to able to specify start and end dates for downloading the data. In this case, I would read my sql database, check for the last downloaded date, pass this into getCoins and append the result into my sql database table. This will be much more efficient then reading the entire dataset daily.

Cheers

**Comment by JesseVent** [comment]
Done, now can pass arguments start_date = 'yyyymmdd' or end_date = 'yyyymmdd' in the getCoins() function. 

I'd recommend just saving the output as a .Rdata file, they have such good compression and so easy to work with.
